# Generated by Django 6.0.3 on 2026-03-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
                ('data_vencimento', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
